# Generated by Django 4.2 on 2023-05-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
